name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    -  run: mvn clean install -pl !cassandra
    -  run: cd cassandra
    - name: Ballerina Build
      uses: ballerina-platform/ballerina-action/@swan-lake-release
      with:
        args:
          build -a -c --skip-tests --sourceroot cassandra
          
